title:        Carlos Cuéllar
tagline:      'UX Designer'
description:  'UX Designer'
url:          https://carloscuellar.net
author:
  name:       'Carlos Cuéllar'
  email:      'uxcuellar@gmail.com'
markdown:     kramdown
permalink:    /blog/:title/
highlighter:  rouge
paginate:     10
paginate_path: /blog/page:num/
host: 0.0.0.0
twitter:
  username: uxcuellar
logo: /apple-touch-icon-precomposed.png
social:
  name: Carlos Cuéllar
  links:
    - https://twitter.com/uxcuellar
    - https://www.linkedin.com/in/uxcuellar
    - https://github.com/uxcuellar
webmaster_verifications:
  google: ZTzErRU2qHFONj6qV8Y0t3_ukyx-MtVQzKWwXq0BPLg
  bing: 019F5FD588A9EE4EF990A4653E7E03C3

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "Carlos Cuéllar"
  -
    scope:
      path: "work/projects/"
    values:
      sitemap: false

# GitHub info
github:
  repo: uxcuellar/uxcuellar.github.io
  branch: master

# Use the following plug-ins
plugins:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed

# Config for atom feed
feed:
  path: atom/index.xml

# Config for post's excerpts
excerpt_separator: <!--more-->

# Prose Config
prose:
  siteurl: "http://carloscuellar.net"
  media: "images"
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"